export enum DIMENSIONS {
    LANDSCAPE = 0,
    PORTRAIT,
    SQUARE,
}


export type AnimItem = {
    id: string,
    pos: { lat: number, lng: number }
    posString: string,
    author: string,
    dateAdded: Date,
    youtubeId: string,
    title: string,
    shorts: boolean,
}


export function fetchAnimItems(): AnimItem[] {
    return [
        {
            id: "1",
            pos: { lat: 53.1424, lng: -7.6921 },
            posString: "Dublin",
            title: "Light in the Darkness",
            author: "Emlyn Boyle",
            dateAdded: new Date(2025, 6, 13),
            youtubeId: "76mqCOKrpaY",
            shorts: false,
        },
        {
            id: "2",
            pos: { lat: 50.8798, lng: 4.7005 },
            posString: "Belguim",
            title: "Bloom",
            author: "Affie De Cooman",
            dateAdded: new Date(2025, 6, 13),
            youtubeId: "7xHW4C9QoRY",
            shorts: false,
        },
        {
            id: "3",
            pos: { lat: 37.5079, lng: 15.0830 },
            posString: "Cantina, Italy",
            title: "Give Peace a Chance",
            author: "Donana Napoli",
            youtubeId: "6Pq-oRP-bJs",
            dateAdded: new Date(2025, 6, 13),
            shorts: false,
        },
        {
            id: "4",
            pos: { lat: 46.5653, lng: -66.4619 },
            posString: "Canada",
            title: "Surveilance",
            author: "Brandon Hicks",
            dateAdded: new Date(2025, 6, 13),
            youtubeId: "Oe-y2XFiuZI",
            shorts: false,
        },
        {
            id: "5",
            pos: { lat: 39.0742, lng: 21.8243 },
            posString: "Greece",
            author: "Konstantinos Kyriakou",
            dateAdded: new Date(2025, 6, 13),
            youtubeId: "PSrN99wuSgU",
            title: "The Sun Thief",
            shorts: false,
        },
        {
            id: "6",
            pos: { lat: 29.749907, lng: -95.358421 },
            posString: "Houston, Texas",
            author: "Felipe Sanchez",
            dateAdded: new Date(2025, 6, 13),
            youtubeId: "qMfRjaARVp4",
            title: "KIDS AND ROCKS",
            shorts: false,
        },

        {
            id: "7",
            title: "I LOVE WATERMELON",
            author: "Leisl Adams",
            posString: "Ottawa, Canada",
            pos: { lat: 45.42153, lng: -75.69719 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "xZFXwUxzjLA",
            shorts: false,

        },
        {
            id: "8",
            title: "WHERE THE OWL APPEARS",
            author: "Shorouk Allam",
            posString: "ASSIUT GOVERNORATE, EGYPT",
            pos: { lat: 26.82055, lng: 30.80250 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "DwDvxZob_Xc",
            shorts: false,
        },
        {
            id: "9",
            title: "Existance is Resistance",
            author: "Lluis Fuzzhound",
            posString: "Valencia, Spain",
            pos: { lat: 39.46991, lng: -0.37629 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "6K627N8zx10",
            shorts: false,
        },
        {
            id: "10",
            title: "FLOWERS OF MY HEART",
            author: "Adnan Hussain",
            posString: "Los Angeles, US",
            pos: { lat: 34.05223, lng: -118.24368 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "tjiTIeh8WYA",
            shorts: true,
        },
        {
            id: "11",
            title: "TO GAZA WITH LOVE",
            author: "Kate Jessop",
            posString: "Brighton, UK",
            pos: { lat: 50.82838, lng: -0.139471 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "yVRvpc7DQNg",
            shorts: false,
        },
        {
            id: "12",
            title: "Seeds",
            author: "Vangelis Karadimas",
            posString: "Athens, Greece",
            pos: { lat: 37.9838, lng: 23.72752 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "GXT3BAYbM6E",
            shorts: false,
        },
        {
            id: "13",
            pos: { lat: 51.76684, lng: 0.47578 },
            posString: "Essex, UK",
            author: "The Mollusc Dimension",
            dateAdded: new Date(2025, 6, 16),
            shorts: false,
            youtubeId: "d9YzUR9NNmo",
            title: "A TINY MESSAGE OF SOLIDARITY",
        },
        {
           id: "14",
            pos: { lat: 19.43260, lng: -99.13319 },
            posString: "Mexico, Mexico City",
            title: "HANDELA BY THE BEACH",
            author: "CUAUHTEMOC PADILLAC",
            youtubeId: "fZVDbCaEcYM",
            shorts: false,
            dateAdded: new Date(2025, 6, 16),
        },
        {
            id: "15",
            title: "OLIVES, FLOWERS & SEA",
            author: "Andrés Puig Sandoval",
            posString: "Madrid, Spain",
            pos: { lat: 40.41650, lng: -3.70256 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "NHFyaUmnhGg",
            shorts: false,
        },
        {
            id: "16",
            title: "PALESTINE YOU ARE THE HEART OF THE WORLD",
            author: "Ixchel Sierra / Candy C. Rivera",
            posString: "Benito Juárez, Mexico",
            pos: { lat: 19.35000, lng: -99.15000 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "hv4LAzEvSxw",
            shorts: false,
        },
        {
            id: "17",
            title: "A SIMPLE TEST",
            author: "Titouan Tillier",
            posString: "Angoulême, France",
            pos: { lat: 45.64842, lng: 0.15519 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "vxsnC6nOJ_M",
            shorts: true,
        },
        {
            id: "18",
            pos: { lat: 52.52, lng: 13.405 },
            title: "Bird",
            author: "Lena Ziyal",
            posString: "Berlin",
            shorts: false,
            youtubeId: "xXLI4QSvOhs",
            dateAdded: new Date(2025, 6, 16),
        },
        {
            id: "19",
            title: "REUNITED",
            author: "Dominique Vettom-Morisod",
            posString: "Geneva, Switzerland",
            pos: { lat: 46.20439, lng: 6.14316 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "mWvTUxccDdg",
            shorts: false,
        },
        {
            id: "20",
            title: "CHILDREN OF WAR",
            author: "Zina Papadopoulou",
            posString: "Athens, Greece",
            pos: { lat: 37.9838, lng: 23.72753 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "mSlATXqkQ9s",
            shorts: false,
        },
        {
            id: "21",
            title: "AFTER THE STORM",
            author: "Ben Adam-Harris",
            posString: "Thame, UK",
            pos: { lat: 51.7484, lng: -0.97624 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "hMbeTEY6zV0",
            shorts: false,
        },
        {
            id: "22",
            title: "FLOWER CHILD",
            author: "Ed Chee",
            posString: "Vancouver, Canada",
            pos: { lat: 49.2827, lng: -123.1207 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "fmrtvRQ1l_g",
            shorts: false,
        },
        {
            id: "23",
            title: "A SMALL WISH",
            author: "Joanne Davis",
            posString: "High Wycombe, UK",
            pos: { lat: 51.6283, lng: -0.7492 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "iGVhI2aYYmc",
            shorts: false,
        },
        {
            id: "24",
            title: "HEAVY HEART",
            author: "Stephen Irwin",
            posString: "Wandsworth",
            pos: { lat: 51.4640, lng: -0.1924 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "jIud-8H4fNU",
            shorts: false,
        },
        {
            id: "25",
            title: "FROM THE ASHES",
            author: "Jamil Lahham / Dan Franke",
            posString: "Montreal/ Stuttgart",
            pos: { lat: 45.5017, lng: -73.5672 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "7NJ_NL_mHR0",
            shorts: false,
        },
        {
            id: "26",
            title: "FROM THE ASHES",
            author: "Jamil Lahham / Dan Franke",
            posString: "Montreal/ Stuttgart",
            pos: { lat: 48.7758, lng: 9.1829 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "7NJ_NL_mHR0",
            shorts: false,
        },
        {
            id: "27",
            title: "EXIST TO RESIST",
            author: "Adarsh Madhusudhanan",
            posString: "Kodungallur, India",
            pos: { lat: 10.2222, lng: 76.1992 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "t1fOV5zBIX4",
            shorts: false,
        },
        {
            id: "28",
            title: "GAZA SEEDS",
            author: "ELISA MARTINEZ",
            posString: "Alicante, Spain",
            pos: { lat: 38.3452, lng: -0.4815 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "SQG1FtBQiv8",
            shorts: false,
        },
        {
            id: "29",
            title: "JUST EATING",
            author: "Mohamed Naser",
            posString: "CAIRO, Egypt",
            pos: { lat: 30.0444, lng: 31.2357 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "rmzqNAIKKrY",
            shorts: true,
        },
        {
            id: "30",
            title: "TO GAZA WITH LOVE",
            author: "Saho Saito",
            posString: "Tokyo, Japan",
            pos: { lat: 35.6895, lng: 139.6917 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "FowPfMj9WYc",
            shorts: false,
        },
        {
            id: "31",
            title: "HEARTS 4 GAZA",
            author: "Bella Woodfield",
            posString: "Cardiff, UK",
            pos: { lat: 51.4816, lng: -3.1790 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "7iTly7Dlwgo",
            shorts: false,
        },

        {
            id: "32",
            title: "DEAR FRIEND",
            author: "Marcia Rojas",
            posString: "Penarth",
            pos: { lat: 51.4352, lng: -3.1740 },
            dateAdded: new Date(2025, 6, 23),
            youtubeId: "PdIPaeCbJ0w",
            shorts: false,
        }, {
            id: "33",
            title: "VOLA!",
            author: "Simone Giampaolo",
            posString: "London",
            pos: { lat: 51.5072, lng: -0.1276 },
            dateAdded: new Date(2025, 6, 23),
            youtubeId: "6W6jB15PW7U",
            shorts: false,
        },
        {
            id: "34",
            title: "KEFFIYEH",
            author: "Nomi Lefort",
            posString: "London",
            pos: { lat: 51.5072, lng: -0.12782 },
            dateAdded: new Date(2025, 6, 23),
            youtubeId: "UwJMOxayzbM",
            shorts: false,
        }, {
            id: "35",
            title: "WE COME TOGETHER",
            author: "Shefalee Jain",
            posString: "Delhi",
            pos: { lat: 28.6139, lng: 77.2090 },
            dateAdded: new Date(2025, 6, 23),
            youtubeId: "VIKgKVsPNms",
            shorts: false,
        }, {
            id: "36",
            title: "A LOAF OF BREAD",
            author: "Tayseera Alaqad",
            posString: "Gaza",
            pos: { lat: 31.5016, lng: 34.4667 },
            dateAdded: new Date(2025, 6, 23),
            youtubeId: "tZVIgXGahS4",
            shorts: false,
        }, {
            id: "37",
            title: "FEATHERS OVER THE CLOUDS",
            author: "Svetlana Gencheva",
            posString: "Paris",
            pos: { lat: 48.8566, lng: 2.3523 },
            dateAdded: new Date(2025, 6, 23),
            youtubeId: "BZzDcrPeD58",
            shorts: false,
        }, {
            id: "38",
            title: "SENDING LOVE",
            author: "Katy Rushton",
            posString: "Manchester",
            pos: { lat: 53.4808, lng: -2.2426 },
            dateAdded: new Date(2025, 6, 23),
            youtubeId: "gDt7exjoWYQ",
            shorts: false,
        }, {
            id: "39",
            title: "A ROSE SHOULDERS UP",
            author: "Isobel May",
            posString: "Farnham",
            pos: { lat: 51.2144, lng: -0.7980 },
            dateAdded: new Date(2025, 6, 23),
            youtubeId: "-kSNc8zYd4M",
            shorts: false,
        }, {
            id: "40",
            title: "RESILIENCE",
            author: "Man Yuk Cheuk",
            posString: "HONG KONG",
            pos: { lat: 22.3193, lng: 114.1694 },
            dateAdded: new Date(2025, 6, 23),
            youtubeId: "nQzuSWO_Xl0",
            shorts: false,
        }, {
            id: "41",
            title: "OLIVE TREES GROW",
            author: "Yesim Caglar",
            posString: "KOCAELI",
            pos: { lat: 40.7654, lng: 29.9406 },
            dateAdded: new Date(2025, 6, 23),
            youtubeId: "pp3qTkK9vRQ",
            shorts: false,
        }, {
            id: "42",
            title: "FAMINE",
            author: "Rehab Ayman",
            posString: "Cairo",
            pos: { lat: 30.0444, lng: 31.2356 },
            dateAdded: new Date(2025, 6, 23),
            youtubeId: "5kbX5PfMO0Q",
            shorts: false,
        },
        {
            id: "43",
            title: "WE ARE THE SEEDS",
            author: "Nour Khamis",
            posString: "LONDON",
            pos: { lat: 51.5074, lng: -0.1280 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "Ni9f_ZZBd6c",
            shorts: false
        },
        {
            id: "44",
            title: "MY SIDE",
            author: "Raul Alejandro Morales Reyes",
            posString: "Mexico City",
            pos: { lat: 19.4326, lng: -99.1332 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "lJPDPje29nc",
            shorts: false
        },
        {
            id: "45",
            title: "NOW",
            author: "Asta Azopardi",
            posString: "LONDON",
            pos: { lat: 51.5074, lng: -0.1282 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "UTlcoH9LjYU",
            shorts: false
        },
        {
            id: "46",
            title: "HIDDEN UNDER THE WINGS",
            author: "Samia Kafati",
            posString: "Montreal",
            pos: { lat: 45.5019, lng: -73.5676 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "n8j4a4joye0",
            shorts: false
        },
        {
            id: "47",
            title: "WE WERE SEEDS",
            author: "Adrián Piqueras Sánchez",
            posString: "MADRID",
            pos: { lat: 40.4168, lng: -3.7038 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "XWuItQ4WwAw",
            shorts: false
        },
        {
            id: "48",
            title: "SEEDS OF FREEDOM",
            author: "Martyna Sabadasz",
            posString: "Cheltenham",
            pos: { lat: 51.9001, lng: -2.0797 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "5giGz57XvTw",
            shorts: false
        },
        {
            id: "49",
            title: "LIKE WILDFLOWERS",
            author: "Lauren Flinner",
            posString: "Saugus",
            pos: { lat: 42.4648, lng: -71.0101 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "6Ab2f57D7R0",
            shorts: false
        },
        {
            id: "50",
            title: "SENDING LOVE",
            author: "Deanna Morse",
            posString: "Junction City",
            pos: { lat: 44.2193, lng: -123.2048 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "Ji9YRNNHi4E",
            shorts: false
        },
        {
            id: "51",
            title: "SAFETY AND PEACE",
            author: "Arran Carey",
            posString: "Cardiff",
            pos: { lat: 51.4816, lng: -3.17915 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "9hC3wwBy4vw",
            shorts: false
        },
        {
            id: "52",
            title: "PEACE PERFORMER",
            author: "Barbara Schedl",
            posString: "Vienna",
            pos: { lat: 48.2082, lng: 16.3738 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "9wUyoWyT1vo",
            shorts: true
        },
        {
            id: "53",
            title: "POTS AND PRAYERS",
            author: "Liz Maelane",
            posString: "Johannesburg",
            pos: { lat: -26.2041, lng: 28.0473 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "ULnp4_JqBac",
            shorts: false
        },
        {
            id: "54",
            title: "BETTER DAYS",
            author: "JULIE AK",
            posString: "Rolle",
            pos: { lat: 46.4578, lng: 6.3398 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "4eXMa3pU1qs",
            shorts: false
        },
        {
            id: "55",
            title: "GROW OLD",
            author: "Eloise Jenninger",
            posString: "Winchester",
            pos: { lat: 51.0629, lng: -1.308 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "rlbBhnW74Ek",
            shorts: false
        },
        {
            id: "56",
            title: "UNITED FOR GAZA",
            author: "Catherine Khounlivong",
            posString: "Rosny-sous-Bois",
            pos: { lat: 48.8708, lng: 2.4903 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "OnLa-X23bhE",
            shorts: false
        },
        {
            id: "57",
            title: "FREE AS THE BIRDS",
            author: "Rachel McBride",
            posString: "Alness",
            pos: { lat: 57.683, lng: -4.250 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "wkdRx1j5zck",
            shorts: false
        },
        {
            id: "58",
            title: "EVERYTHING IN THIS WORLD",
            author: "James Thacher",
            posString: "Brant Rock",
            pos: { lat: 42.0807, lng: -70.9954 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "wHzkyLcgvpY",
            shorts: false
        },
        {
            id: "59",
            title: "A BOAT TO PALESTINE",
            author: "Branko Solce",
            posString: "Ljubljana",
            pos: { lat: 46.0569, lng: 14.5058 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "9adqR7dUvXE",
            shorts: false
        },
        {
            id: "60",
            title: "BOOK FOR PALESTINE",
            author: "Sara Buitrago, Michel Buitrago, María Bermúdez, Deiverly Cordones",
            posString: "Bogotá",
            pos: { lat: 4.711, lng: -74.07214 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "84aclt0dwzU",
            shorts: false
        },
        {
            id: "61",
            title: "OLIVE",
            author: "Valeria Weerasinghe",
            posString: "Gallarate",
            pos: { lat: 45.6606, lng: 8.7934 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "72vZbwIBJMU",
            shorts: false
        },
        {
            id: "62",
            title: "HOPE",
            author: "Subhan Zafar",
            posString: "Leicester",
            pos: { lat: 52.6369, lng: -1.1398 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "zyswgmbYezQ",
            shorts: false
        },
        {
            id: "63",
            title: "WAR IS NOT JUST NEWS",
            author: "Zahra Arabi",
            posString: "Tehran",
            pos: { lat: 35.6892, lng: 51.389 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "S7VIC0g55Sw",
            shorts: false
        },
        {
            id: "64",
            title: "INTIFADA'S CHILDREN",
            author: "Sampriti Dasgupta",
            posString: "Kolkata",
            pos: { lat: 22.5726, lng: 88.36391 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "Ga27ev1gWi8",
            shorts: false
        },
        {
            id: "65",
            title: "ANIJAM from FMK Workshop",
            author: "Viola Mancini",
            posString: "Pordenone",
            pos: { lat: 45.9569, lng: 12.6605 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "PgQJpw2evUE",
            shorts: false
        },
        {
            id: "66",
            title: "RESCUE DRAWS",
            author: "Diana Cortés & Antonio Pastor",
            posString: "Alcoy",
            pos: { lat: 38.698, lng: -0.4743 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "0tt9ahnRejI",
            shorts: false
        },
        {
            id: "67",
            title: "DEAR CHILDREN OF GAZA",
            author: "Tony Gammidge",
            posString: "Brighton",
            pos: { lat: 50.82838, lng: -0.13946 },
            dateAdded: new Date(2025, 6, 29),
            youtubeId: "PWi6xVPHTsM",
            shorts: false
        },
        {
            id: "68",
            title: "KITE CIRCUS DRONE",
            author: "Rachel Dring",
            posString: "Hackney",
            pos: { lat: 51.545, lng: -0.0551 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "k-Q4AZ0iibY",
            shorts: false
        },
        {
            id: "69",
            title: "GAZA FILM KIDS",
            author: "Sam Fell",
            posString: "London",
            pos: { lat: 51.5074, lng: -0.1279 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "9-S6Num04ak",
            shorts: false
        },
        {
            id: "70",
            title: "SEEDS OF PEACE",
            author: "Geoffrey Beatty",
            posString: "Philadelphia",
            pos: { lat: 39.9526, lng: -75.1652 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "cHhz1fnGnDc",
            shorts: false
        },
        {
            id: "71",
            title: "POPPY",
            author: "Anne McCall",
            posString: "Austin",
            pos: { lat: 30.2672, lng: -97.7431 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "kwMGmLf7w-Q",
            shorts: false
        },
        {
            id: "72",
            title: "DESERT ROSE",
            author: "Bonobithi Biswas",
            posString: "Montrouge",
            pos: { lat: 48.8166, lng: 2.3136 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "Xkrblg5InDA",
            shorts: false
        },
        {
            id: "73",
            title: "THREE SCENES FROM GAZA",
            author: "Claudia Munksgaard-Palmqvist",
            posString: "Copenhagen",
            pos: { lat: 55.6761, lng: 12.5683 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "I9BDgwuevnc",
            shorts: false
        },
        {
            id: "74",
            title: "THEIR SKIES CRY BUT DREAMS STILL RISE",
            author: "Salma Lrhayyate",
            posString: "Brussels",
            pos: { lat: 50.85045, lng: 4.34878 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "Bkcz7qYluMo",
            shorts: false
        },
        {
            id: "75",
            title: "DON-KEY",
            author: "ERICK CUEVAS",
            posString: "L’Aquila",
            pos: { lat: 42.3506, lng: 13.3995 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "fWLhJHYy6Gs",
            shorts: false
        },
        {
            id: "76",
            title: "WHEN BUTTERFLIES ARE SUBJECTED TO WIND",
            author: "Hannaneh Vahedi",
            posString: "Tehran",
            pos: { lat: 35.6892, lng: 51.3891 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "OolXjYsQXuk",
            shorts: false
        },
        {
            id: "77",
            title: "SILHOUETTE",
            author: "Maliheh Gholamzadeh",
            posString: "Birmingham",
            pos: { lat: 52.4862, lng: -1.8904 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "yrajlz3BF44",
            shorts: false
        },
        {
            id: "78",
            title: "Watermelon and Dandelion",
            author: "Sam Chou",
            posString: "Toronto",
            pos: { lat: 43.6511, lng: -79.3839 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "P8qw3Nxsp0E",
            shorts: false
        },
        {
            id: "79",
            title: "LOVE TO GAZA",
            author: "victoria lungu",
            posString: "Leeds",
            pos: { lat: 53.8008, lng: -1.5491 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "VeL9wkFuh0k",
            shorts: false
        },
        {
            id: "80",
            title: "WHAT, WHEN?",
            author: "Eleni Aerts",
            posString: "Ieper",
            pos: { lat: 50.8512, lng: 2.8857 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "GXf81DYoau4",
            shorts: false
        },
        {
            id: "81",
            title: "FOR THE CHILDREN WITH LOVE",
            author: "Shreyasi Das",
            posString: "Montreal",
            pos: { lat: 45.5019, lng: -73.5671 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "0BADhN0TEtk",
            shorts: false
        },
        {
            id: "82",
            title: "WE ARE FAMILIES",
            author: "Billy Mpetha",
            posString: "Stockport",
            pos: { lat: 53.4106, lng: -2.1575 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "PFB02C3Ru24",
            shorts: false
        },
        {
            id: "83",
            title: "DECOLONIZED DANCE",
            author: "Zeinab Araghinia",
            posString: "Babol",
            pos: { lat: 36.5519, lng: 52.6789 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "rgErQqD9E0A",
            shorts: false
        },
        {
            id: "84",
            title: "THE WALK",
            author: "Xavier Aguayo",
            posString: "Quito",
            pos: { lat: -0.1807, lng: -78.4678 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "oLV9hF_zpxo",
            shorts: false
        },
        {
            id: "85",
            title: "TAKE HANDS",
            author: "Diek Grobler",
            posString: "Pretoria",
            pos: { lat: -25.7479, lng: 28.2293 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "FgKN3T42Y4A",
            shorts: false
        },
        {
            id: "86",
            title: "PRESSED FLOWERS",
            author: "Elizabeth Hobbs",
            posString: "LONDON",
            pos: { lat: 51.5074, lng: -0.1274 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "0I8Hd9UGmzg",
            shorts: false
        },
        {
            id: "87",
            title: "FLYING FREE",
            author: "Christina Booth",
            posString: "Bristol",
            pos: { lat: 51.4545, lng: -2.58793 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "yvsM1VbVs6k",
            shorts: false
        },
        {
            id: "88",
            title: "HEAVEN",
            author: "Alheli Ochoa",
            posString: "Azcapotzalco",
            pos: { lat: 19.485, lng: -99.172 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "Z4LNxrVBl6o",
            shorts: false
        },
        {
            id: "89",
            title: "ARI",
            author: "Rodrigo Del Pino",
            posString: "Buenos Aires",
            pos: { lat: -34.6037, lng: -58.3816 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "JReNR4-amI8",
            shorts: false
        },
        {
            id: "90",
            title: "HUG OF PEACE (ABRAZODEPAZ)",
            author: "Rulo Mileg",
            posString: "Guatemala City",
            pos: { lat: 14.6349, lng: -90.5069 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "q5McefhwQwE",
            shorts: false
        },
        {
            id: "91",
            title: "THE POEM",
            author: "Drew de Silva",
            posString: "Colombo",
            pos: { lat: 6.9271, lng: 79.8612 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "pmXHr5Orby0",
            shorts: false
        },
        {
            id: "92",
            title: "TO GAZA WITH LOVE",
            author: "Gareth Bennett",
            posString: "Newport",
            pos: { lat: 51.5842, lng: -2.9977 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "SYgmG6q92DY",
            shorts: false
        },
        {
            id: "93",
            title: "SEED WALKER",
            author: "Sara Forero, María José Ramírez, Joe Vásquezl, Mallivi Melo Rey",
            posString: "Bogotá",
            pos: { lat: 4.711, lng: -74.0720 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "86fzgJqk1ok",
            shorts: false
        },
        {
            id: "94",
            title: "SEED OF PEACE",
            author: "Fergy Bustacara, Mallivi Melo Rey, Cielo Forero",
            posString: "Bogotá",
            pos: { lat: 4.711, lng: -74.0719 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "vyUfZvowGA8",
            shorts: false
        },
        {
            id: "95",
            title: "LUZ",
            author: "Ben Fox",
            posString: "London",
            pos: { lat: 51.5074, lng: -0.1277 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "twH59oMNRl8",
            shorts: false
        },
        {
            id: "96",
            title: "RED WAVE",
            author: "Esther Vital",
            posString: "Zaragoza",
            pos: { lat: 41.6488, lng: -0.8891 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "MtNobDIp10A",
            shorts: false
        },
        {
            id: "97",
            title: "LOVE TO GAZA",
            author: "Brenda Goodchild",
            posString: "Reading",
            pos: { lat: 51.4543, lng: -0.9781 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "1iUVehppg_E",
            shorts: false
        },
        {
            id: "98",
            title: "ANIMONTAGE",
            author: "Alissar Kobeissi",
            posString: "Vancouver",
            pos: { lat: 49.2827, lng: -123.1205 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "Uvl2CYfQT08",
            shorts: true
        },
        {
            id: "99",
            title: "FREE PALESTINE",
            author: "Navaporn Boonmasiri",
            posString: "Vancouver",
            pos: { lat: 49.2827, lng: -123.1206 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "MKy6jzaBEac",
            shorts: false
        },
        {
            id: "100",
            title: "BACK HOME",
            author: "Chiara Carnovale",
            posString: "Paola",
            pos: { lat: 39.3667, lng: 16.0333 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "912Yfo-eI8Y",
            shorts: false
        },
        {
            id: "101",
            title: "PEACE FOR THE CHILDREN OF PALESTINE",
            author: "Maria Tsakiri",
            posString: "Edinburgh",
            pos: { lat: 55.9533, lng: -3.1883 },
            dateAdded: new Date(2025, 6, 31),
            youtubeId: "_gdv-2G7M4s",
            shorts: true
        },
        {
            id: "102",
            title: "VIVA VIVA GAZA",
            author: "Anna Benner",
            posString: "Berlin",
            pos: { lat: 52.52, lng: 13.404 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "1xL7ugU9DSg",
            shorts: false
        },
        {
            id: "103",
            title: "EVERY SOUND IS A HEART BEAT",
            author: "Helen Anderson",
            posString: "Cardiff",
            pos: { lat: 51.4816, lng: -3.17911 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "u5Z96_JMJCQ",
            shorts: false
        },
        {
            id: "104",
            title: "ENDLESS LOVE",
            author: "Megan Wennberg",
            posString: "Waverley",
            pos: { lat: 38.0591, lng: -120.9344 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "mmaj9-JK5pk",
            shorts: false
        },
        {
            id: "105",
            title: "PALESTINE PERSISTS",
            author: "Lama Mohamed",
            posString: "Silver Spring",
            pos: { lat: 38.9907, lng: -77.0261 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "vwzHnNGgzzE",
            shorts: false
        },
        {
            id: "106",
            title: "FREE WATERMELON",
            author: "Parsa Parsselo",
            posString: "Tehran",
            pos: { lat: 35.6892, lng: 51.3892 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "Xx6TYRAjMbg",
            shorts: false
        },
        {
            id: "107",
            title: "HOME GROWN",
            author: "Ben Cady",
            posString: "Belfast",
            pos: { lat: 54.5973, lng: -5.9301 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "MvI_lrOMmZ0",
            shorts: false
        },
        {
            id: "108",
            title: "LAND OF OLIVES",
            author: "Sonia Uppal",
            posString: "London",
            pos: { lat: 51.5074, lng: -0.12783 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "mTly72Ut2mw",
            shorts: false
        },
        {
            id: "109",
            title: "WITH LOVE, FOR THE CHILDREN OF GAZA",
            author: "Miwa Matreyek",
            posString: "Vancouver",
            pos: { lat: 49.2827, lng: -123.1209 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "8Ihiw2uRnP0",
            shorts: false
        },
        {
             id: "110",
            title: "A NEW MORNING",
            author: "Marie-Josée Parent",
            posString: "Montreal",
            pos: { lat: 45.5019, lng: -73.5675 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "uMO5AQ4FOkM",
            shorts: false
        },
        {
            id: "111",
            title: "BIRDSONG",
            author: "Ivan s",
            posString: "Angoulême",
            pos: { lat: 45.6484, lng: 0.1562 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "6oyrJ9lzZh8",
            shorts: false
        },
        {
            id: "112",
            title: "BETTER RAIN SEEDS",
            author: "Francesca visocchi",
            posString: "Rome",
            pos: { lat: 41.9028, lng: 12.4964 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "imA7gK20mis",
            shorts: false
        },
        {
            id: "113",
            title: "YOU MUST LIVE",
            author: "Miriam Yoo",
            posString: "Staten Island",
            pos: { lat: 40.5795, lng: -74.1502 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "u8urQFoNLz8",
            shorts: false
        },
        {
            id: "114",
            title: "WITH LOVE FROM CARDIFF",
            author: "Cardiff Animation Festival",
            posString: "Cardiff",
            pos: { lat: 51.4816, lng: -3.17912 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "9FTDzWhoJR4",
            shorts: false
        },
        {
            id: "115",
            title: "TOGETHER WE CAN MOVE",
            author: "Muhammad Ahmad Saleem",
            posString: "Lahore",
            pos: { lat: 31.5497, lng: 74.3436 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "pPxa5y_0G4w",
            shorts: true
        },
        {
            id: "116",
            title: "COLORS DANCE",
            author: "Daniela Godel",
            posString: "Barcelona",
            pos: { lat: 41.3851, lng: 2.1734 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "f07klMzSL_I",
            shorts: false
        },
        {
            id: "117",
            title: "TO GAZA WITH LOVE",
            author: "Gemma Rigg",
            posString: "Bristol",
            pos: { lat: 51.4545, lng: -2.58791 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "uVX649UPl_E",
            shorts: false
        },
        {
            id: "118",
            title: "TO THE YOUNG ARTIST OF GAZA",
            author: "Aaron Dunbar",
            posString: "Lowell",
            pos: { lat: 42.6334, lng: -71.3162 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "h6oBcg8owWY",
            shorts: false
        },
        {
            id: "119",
            title: "راحة",
            author: "Alaric Uiterwijk",
            posString: "Utrecht",
            pos: { lat: 52.0907, lng: 5.1214 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "IhMseveRjGU",
            shorts: false
        },
        {
            id: "120",
            title: "WE COUNT THE DAYS",
            author: "Francesca Loss",
            posString: "Dax",
            pos: { lat: 43.7108, lng: -1.0536 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "GQBzio2koSY",
            shorts: false
        },
        {
            id: "121",
            title: "WATERMELON",
            author: "Ilaina Lowe",
            posString: "Bristol",
            pos: { lat: 51.4545, lng: -2.58792 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "MCHE5Oaot6s",
            shorts: false
        },
        {
            id: "122",
            title: "WAR VS PEACE",
            author: "Tehzeeb Khurana",
            posString: "Mumbai",
            pos: { lat: 19.076, lng: 72.87771 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "Kt-sd-AlN14",
            shorts: false
        },
        {
            id: "123",
            title: "VIVA PALESTINE",
            author: "Hamish Dodd",
            posString: "Tower Hamlets",
            pos: { lat: 51.5202, lng: -0.0296 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "6BYXAJwM1go",
            shorts: false
        },
        {
            id: "124",
            title: "WEAVING FOR PEACE",
            author: "Gabh Ar",
            posString: "Paris",
            pos: { lat: 48.8566, lng: 2.3524 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "G_L7yw8e5Pg",
            shorts: true
        },
        {
            id: "125",
            title: "WE WILL FLOAT",
            author: "Laila Nunez",
            posString: "Mexico City",
            pos: { lat: 19.4326, lng: -99.13321 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "G1yZwnB5jXI",
            shorts: false
        },
        {
            id: "126",
            title: "WE ARE ALL PALESTINE",
            author: "Manuela Gandra",
            posString: "Lisbon",
            pos: { lat: 38.7169, lng: -9.13993 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "dG6zSuLjtPo",
            shorts: false
        },
        {
            id: "127",
            title: "UMUNTU NGUMUNTU NGABANTU",
            author: "Jenna van Noie",
            posString: "Cape Town",
            pos: { lat: -33.9249, lng: 18.4241 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "l3w4pcXEWAU",
            shorts: false
        },
        {
            id: "128",
            title: "TO GAZA",
            author: "Agnes Patron",
            posString: "Villeneuve-la-Garenne",
            pos: { lat: 48.9347, lng: 2.3278 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "GNA7dt70k8Y",
            shorts: false
        },
        {
            id: "129",
            title: "THE SEEDS OF LOVE",
            author: "Zsófia Börcsök",
            posString: "Budapest",
            pos: { lat: 47.4979, lng: 19.0402 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "Er0AYRjeGA0",
            shorts: false
        },
        {
            id: "130",
            title: "SENDING LOVE FROM GRONINGEN",
            author: "Sophie Spendel",
            posString: "Groningen",
            pos: { lat: 53.2194, lng: 6.5665 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "dSBqNdMMluo",
            shorts: false
        },
        {
            id: "131",
            title: "PUERTO RICO CON PALESTINA",
            author: "Pedro Vargas",
            posString: "Guaynabo",
            pos: { lat: 18.3564, lng: -66.11 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "PjHoCBZXjLU",
            shorts: false
        },
        {
            id: "132",
            title: "FLOSS",
            author: "Adolfo Di Molfetta",
            posString: "Bisceglie",
            pos: { lat: 41.2411, lng: 16.5033 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "Pono-l8wcVQ",
            shorts: false
        },
        {
            id: "133",
            title: "AZEITONAS",
            author: "Camila Kater",
            posString: "Atibaia",
            pos: { lat: -23.1175, lng: -46.5569 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "mtW2UCFDrW0",
            shorts: false
        },
        {
            id: "134",
            title: "AZIZI",
            author: "Sukanya Paul",
            posString: "Mumbai",
            pos: { lat: 19.076, lng: 72.87772 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "Qu48g61f5rI",
            shorts: false
        },
        {
            id: "135",
            title: "THE BIRD OF PALESTINE",
            author: "Anna Langley-Smith",
            posString: "Exeter",
            pos: { lat: 50.7184, lng: -3.5339 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "fBToBA1Npqo",
            shorts: true
        },
        {
            id: "136",
            title: "CEASE FIRE NOW",
            author: "Juliette Pons",
            posString: "Brussels",
            pos: { lat: 50.85045, lng: 4.348781 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "Qq_zRR8Hr0I",
            shorts: false
        },
        {
            id: "137",
            title: "OLIVES 4 FREEDOM",
            author: "Rafaella Milani Santos",
            posString: "São Paulo",
            pos: { lat: -23.5505, lng: -46.6333 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "JI4Ew0nHXR0",
            shorts: false
        },
        {
            id: "138",
            title: "HOPE",
            author: "Rachael Ball",
            posString: "London",
            pos: { lat: 51.5074, lng: -0.12781 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "9-bVMzdcpFA",
            shorts: false
        },
        {
            id: "139",
            title: "I WANT TO BE A DOVE",
            author: "Maria Bouchard",
            posString: "New York City",
            pos: { lat: 40.7128, lng: -74.006 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "jQui5Hy69lI",
            shorts: false
        },
        {
            id: "140",
            title: "CHICKEN AND WATERMELON",
            author: "Angie Canastero, Mallivi Melo",
            posString: "Bogotá",
            pos: { lat: 4.711, lng: -74.0722 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "C42Q1aBSKTc",
            shorts: false
        },
        {
            id: "141",
            title: "COUNTLESS STARS",
            author: "Papaefthymiou Dimitra",
            posString: "Athens",
            pos: { lat: 37.9838, lng: 23.72754 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "T3mlT5vnjrA",
            shorts: false
        },
        {
            id: "142",
            title: "EMBRACE",
            author: "Kristina Yee",
            posString: "Dublin",
            pos: { lat: 53.1424, lng: -7.69211 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "GiaJ0SHHnvU",
            shorts: false
        },
        {
            id: "143",
            title: "FREE",
            author: "Isaiah Zachariah",
            posString: "Naaldwijk",
            pos: { lat: 51.9947, lng: 4.2094 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "y0bau-U1BH8",
            shorts: false
        },
        {
            id: "144",
            title: "FREE PALESTINE",
            author: "Alison Nowak",
            posString: "Minneapolis",
            pos: { lat: 44.9778, lng: -93.265 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "9ksY03m5exQ",
            shorts: false
        },
        {
            id: "145",
            title: "FREE PALESTINE",
            author: "Jin Lim",
            posString: "Fort Lee",
            pos: { lat: 40.8509, lng: -73.9701 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "YlV4-QvMtDg",
            shorts: false
        },
        {
            id: "146",
            title: "IF I MUST DIE",
            author: "Lena, Padelis Ziyal, Paradisis",
            posString: "Thessaloniki",
            pos: { lat: 40.6401, lng: 22.9444 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "A6amBWVdz9o",
            shorts: false
        },
        {
            id: "147",
            title: "IT WILL RETURN AS IT WAS",
            author: "Shroomaster A",
            posString: "Riyadh",
            pos: { lat: 24.7136, lng: 46.6753 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "a-lilJ2tHQY",
            shorts: false
        },
        {
            id: "148",
            title: "LOVE IS IN THE AIR",
            author: "LUCIEN Paul",
            posString: "Annecy",
            pos: { lat: 45.89925, lng: 6.12938 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "nnzTbNLoNrc",
            shorts: false
        },
        {
            id: "149",
            title: "IRIS HAYNEI - THE FLOWERS OF PALESTINE",
            author: "William Osborne",
            posString: "Cardiff",
            pos: { lat: 51.4816, lng: -3.17913 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "ysvNHSUH9yQ",
            shorts: false
        },
        {
            id: "150",
            title: "PALESTINE PALADIN",
            author: "Tomas Jason Roberts",
            posString: "Port Talbot",
            pos: { lat: 51.5954, lng: -3.7847 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "iI1IxDdquto",
            shorts: false
        },
        {
            id: "151",
            title: "THE FREEDOM TO PLAY",
            author: "Abbie O'Shea",
            posString: "Croydon",
            pos: { lat: 51.3765, lng: -0.1006 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "lJzwVNwRMf4",
            shorts: false
        },
        {
            id: "152",
            title: "T0 GAZA WITH LOVE",
            author: "Zoe medcraft",
            posString: "Melbourne",
            pos: { lat: -37.8136, lng: 144.9631 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "10BoM1jiDww",
            shorts: false
        },
        {
            id: "153",
            title: "THE SEA",
            author: "Karla Monterrosa",
            posString: "Richmond",
            pos: { lat: 49.1666, lng: -123.1336 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "wlBQ5BeSkIs",
            shorts: false
        },
        {
            id: "154",
            title: "FOREVER",
            author: "Brian Smee, Isabelle Aspin",
            posString: "Los Angeles",
            pos: { lat: 34.05223, lng: -118.24369 },
            dateAdded: new Date(2025, 7, 3),
            youtubeId: "HANMRZnYPlM",
            shorts: false
        },
        {
            id: "155",
            title: "THE TIMES WILL COME",
            author: "Emile Maigyte",
            posString: "Vilnius",
            pos: { lat: 54.6872, lng: 25.2797 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "-tRGtrTClCM",
            shorts: false
        },
        {
            id: "156",
            title: "TO THE SEA",
            author: "Zareena Raynor",
            posString: "London",
            pos: { lat: 51.5074, lng: -0.12787 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "dPSZOigcQSs",
            shorts: false
        },
        {
            id: "157",
            title: "TO GAZA WITH LOVE",
            author: "Bruce Alcock",
            posString: "Newfoundland",
            pos: { lat: 48.0, lng: -56.0 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "M_uFFIv-bZM",
            shorts: false
        },
        {
            id: "158",
            title: "TO GAZA WITH LOVE",
            author: "Bruce Alcock",
            posString: "Labrador",
            pos: { lat: 53.0000, lng: -60.0000 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "M_uFFIv-bZM",
            shorts: false
        },
        {
            id: "159",
            title: "WHAT IS THERE TO SAY",
            author: "Maja Duvnjak",
            posString: "Oslo",
            pos: { lat: 59.9139, lng: 10.7522 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "lsWe7OeDDmk",
            shorts: false
        },
        {
            id: "160",
            title: "HEARTS ROOTED DOVE",
            author: "Kim Noce",
            posString: "Jongno-gu",
            pos: { lat: 37.5729, lng: 126.9794 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "Eo4QiCkyeoA",
            shorts: false
        },
        {
            id: "161",
            title: "HEARTS ROOTED DOVE",
            author: "Kim Noce",
            posString: "Brighton",
            pos: { lat: 50.82838, lng: -0.139472 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "Eo4QiCkyeoA",
            shorts: false
        },
        {
            id: "162",
            title: "HEARTS ROOTED DOVE",
            author: "Kim Noce",
            posString: "Milan",
            pos: { lat: 45.4642, lng: 9.19 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "Eo4QiCkyeoA",
            shorts: false
        },
        {
            id: "163",
            title: "PALESTINE IS STRONGER",
            author: "Paula Arenas, Isabella Salazar, Mallivi Melo Rey",
            posString: "Bogotá",
            pos: { lat: 4.711, lng: -74.0723 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "DVTNZkjyY0c",
            shorts: false
        },
        {
            id: "164",
            title: "PALESTINE RESILIENCE",
            author: "Pilar Silva, Edwin Molina, Santiago García, Adrián Pérez, Paula Angarita, Mafe Villarraga, Ángel Barrios, Mallivi Melo Rey",
            posString: "Bogotá",
            pos: { lat: 4.711, lng: -74.0724 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "hz9pYAUKRes",
            shorts: false
        },
        {
            id: "165",
            title: "WATERMELON TREE",
            author: "Alison Bonilla, Stephany Torres, Mallivi Melo",
            posString: "Bogotá",
            pos: { lat: 4.711, lng: -74.07210 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "qL5muRnDBdY",
            shorts: false
        },
        {
            id: "166",
            title: "CLAMOR",
            author: "Andrew Velasco",
            posString: "Granada",
            pos: { lat: 37.1773, lng: -3.5986 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "ofwlJDbx8qU",
            shorts: false
        },
        {
            id: "167",
            title: "FREE PALESTINE",
            author: "Candice Weber",
            posString: "Vancouver",
            pos: { lat: 49.2827, lng: -123.1210 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "vkI5mo6Nys8",
            shorts: false
        },
        {
            id: "168",
            title: "J'AI HAÏ LA POÉSIE",
            author: "Charline Pierret, Raphaëlle PRUD’HOMME",
            posString: "Lille",
            pos: { lat: 50.6292, lng: 3.0573 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "lPs1yci--Jc",
            shorts: false
        },
        {
            id: "169",
            title: "THE SUNBIRDS",
            author: "Reena Devani",
            posString: "Mississauga",
            pos: { lat: 43.589, lng: -79.6441 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "YCr9JVkDd_E",
            shorts: false
        },
        {
            id: "170",
            title: "LONDON STANDS WITH PALESTINE",
            author: "ANA PARRA",
            posString: "London",
            pos: { lat: 51.545, lng: -0.0550 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "0Zxeyvn0iZo",
            shorts: false
        },
        {
             id: "171",
            title: "PALESTINA RHYDD",
            author: "Tad Davies",
            posString: "Cardiff",
            pos: { lat: 51.4816, lng: -3.1791 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "WBgP5xzqhoo",
            shorts: false
        },
        {
            id: "172",
            title: "PALESTINE SUNBIRD",
            author: "Andrea Robles",
            posString: "San Juan",
            pos: { lat: 18.4655, lng: -66.1057 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "_EO2l8VPi60",
            shorts: false
        },
        {
            id: "173",
            title: "DRAWING ON HOPE",
            author: "Vivi Markatos",
            posString: "Bracknell",
            pos: { lat: 51.4163, lng: -0.7498 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "WFEaRPgpGkE",
            shorts: false
        },
        {
            id: "174",
            title: "REGROWTH",
            author: "Jonathan Arkema",
            posString: "Zwolle",
            pos: { lat: 52.5126, lng: 6.094 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "2AhrmKoH6NA",
            shorts: false
        },
        {
            id: "175",
            title: "FATAYAR FLOTILA",
            author: "Nani Bhat",
            posString: "Seattle",
            pos: { lat: 47.6062, lng: -122.3321 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "drnOCx_gOlE",
            shorts: false
        },
        {
            id: "176",
            title: "ACROSS THE SEA",
            author: "Diyala Muir",
            posString: "Nicosia",
            pos: { lat: 35.1856, lng: 33.3823 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "O-NSjvL28dY",
            shorts: false
        },
        {
            id: "177",
            title: "ALL EYES ON GAZA",
            author: "Gabriele Barrocu",
            posString: "Arcore",
            pos: { lat: 45.62, lng: 9.281 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "CkTsd-3R5to",
            shorts: false
        },
        {
            id: "178",
            title: "BLODEUO OR LLUDW (BLOOMING FROM THE ASHES)",
            author: "Lleucu Non",
            posString: "London",
            pos: { lat: 51.5074, lng: -0.12786 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "V7wAOXslYI0",
            shorts: false
        },
        {
            id: "179",
            title: "FREE PALESTINE",
            author: "Nina Niué",
            posString: "Amsterdam",
            pos: { lat: 52.37403, lng: 4.88969 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "sOB5jkJWWwY",
            shorts: false
        },
        {
            id: "180",
            title: "LAS FLORES (FLOWERS)",
            author: "Arath Emanuel Turrubiates López",
            posString: "Metepec",
            pos: { lat: 19.251, lng: -99.606 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "ChUISYb5puM",
            shorts: false
        },
        {
            id: "181",
            title: "LET PALESTINE LIVE",
            author: "Monami Roy",
            posString: "Kolkata",
            pos: { lat: 22.5726, lng: 88.3639 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "cg0-EciBwwo",
            shorts: false
        },
        {
            id: "182",
            title: "LOVE WINS",
            author: "Jason Giglio",
            posString: "Portland",
            pos: { lat: 45.5051, lng: -122.675 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "ab9IssX8nyw",
            shorts: false
        },
        {
            id: "183",
            title: "SABAR",
            author: "Elisa Bonandin",
            posString: "Venice",
            pos: { lat: 45.4408, lng: 12.3155 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "-WdHg-cnX0Y",
            shorts: false
        },
        {
            id: "184",
            title: "VORTEX OF LOVE",
            author: "Marjorie Lemay",
            posString: "Montreal",
            pos: { lat: 45.5019, lng: -73.5673 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "tEDlhJhSW08",
            shorts: false
        },
        {
            id: "185",
            title: "DAWN CHORUS",
            author: "Claire Winter",
            posString: "London",
            pos: { lat: 51.538, lng: -0.0996 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "-bAvtc7mpDs",
            shorts: false
        },
        {
            id: "186",
            title: "THE SEED FAMILY",
            author: "Eyder Hernández, Yerikson Soto, Óscar Delgado, Mallivi Melo Rey",
            posString: "Bogotá",
            pos: { lat: 4.711, lng: -74.07215 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "tJ3RaNUzjrI",
            shorts: false
        },
        {
            id: "187",
            title: "GRANDMAS FLOWERS",
            author: "Sylwia Szkiladz, Helena Szkiladz",
            posString: "Suprasl",
            pos: { lat: 53.2056, lng: 23.3406 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "TBD2lydAMcc",
            shorts: false
        },
        {
            id: "188",
            title: "WHERE DO I GO?",
            author: "Zehra Abbas",
            posString: "Karachi",
            pos: { lat: 24.8607, lng: 67.0011 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "sEY8JImoQvM",
            shorts: false
        },
        {
            id: "189",
            title: "GAZA ON MY MIND",
            author: "Daniel Sterlin-Altman",
            posString: "Berlin",
            pos: { lat: 52.52, lng: 13.406 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "Nr0BL-zmUrM",
            shorts: false
        },
        {
            id: "190",
            title: "SOLIDARITY",
            author: "Amanda Bonaiuto",
            posString: "Brooklyn",
            pos: { lat: 40.6782, lng: -73.9442 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "aemqRPYg-Y0",
            shorts: false
        },
        {
            id: "191",
            title: "BEACH SCENE",
            author: "Andrea Tuttrup",
            posString: "Glendale",
            pos: { lat: 34.1425, lng: -118.2551 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "o4aBb9sqXpQ",
            shorts: false
        },
        {
            id: "192",
            title: "WHERE ALL FELL SILENT",
            author: "Jaime Freire",
            posString: "Santiago",
            pos: { lat: -33.4489, lng: -70.6693 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "Y5F8uL5OP0I",
            shorts: false
        },
        {
            id: "193",
            title: "MEMORY",
            author: "Noémie Besombes",
            posString: "Prague",
            pos: { lat: 50.0755, lng: 14.4378 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "mMPHzvGgbrU",
            shorts: false
        },
        {
            id: "194",
            title: "MANY HEARTS",
            author: "Rhiannon Vignes",
            posString: "London",
            pos: { lat: 51.5074, lng: -0.12789 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "fqxhdrpIcqQ",
            shorts: false
        },
        {
            id: "195",
            title: "ONE",
            author: "Sam Decoste",
            posString: "Halifax",
            pos: { lat: 44.6488, lng: -63.5752 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "UiMCHJshfzk",
            shorts: false
        },
        {
            id: "196",
            title: "FREE PALESTINE",
            author: "Laura Ibáñez López",
            posString: "Donostia",
            pos: { lat: 43.3183, lng: -1.9812 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "FD3tKGYbgG0",
            shorts: false
        },
        {
            id: "197",
            title: "FREE PALESTINE",
            author: "Laura Ibáñez López",
            posString: "San Sebastian",
            pos: { lat: 43.3183, lng: -1.9812 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "FD3tKGYbgG0",
            shorts: false
        },
        {
            id: "198",
            title: "THE INEXTENGUISHABLE FIRE OF HOPE",
            author: "Alessandro Amoresano",
            posString: "Naples",
            pos: { lat: 40.8518, lng: 14.2681 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "i6aY0pdGWUA",
            shorts: false
        },
        {
            id: "199",
            title: "HOPE IN THE DARK",
            author: "zayd lokhandwala",
            posString: "Mumbai",
            pos: { lat: 19.076, lng: 72.87773 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "OglMFm4tFaQ",
            shorts: false
        },
        {
            id: "200",
            title: "OUR ASHES ARE ALIVE",
            author: "Vanessa Ferle",
            posString: "Athens",
            pos: { lat: 37.9838, lng: 23.72750 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "nYvftsxJC4k",
            shorts: false
        },
        {
            id: "201",
            title: "RIND AND SEED",
            author: "Syed Haider Naveed",
            posString: "Lahore",
            pos: { lat: 31.5497, lng: 74.34361 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "oMPnEcGTz-s",
            shorts: false
        },
        {
            id: "202",
            title: "WILL FLOURISH",
            author: "Jessica Aline Da Costa",
            posString: "São Bernardo do Campo",
            pos: { lat: -23.6939, lng: -46.565 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "pc-dpM84T50",
            shorts: false
        },
        {
            id: "203",
            title: "THE CAT WITH THE KEFFIYEH",
            author: "Vanessa Ferle",
            posString: "Athens",
            pos: { lat: 37.9838, lng: 23.72751 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "0ES9FHjnrp0",
            shorts: false
        },
        {
            id: "204",
            title: "PROTECT LIFE",
            author: "Christina Nerland",
            posString: "Malvik",
            pos: { lat: 63.4103, lng: 10.6836 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "u0ANpJatrBU",
            shorts: true
        },
        {
            id: "205",
            title: "FROM THE ASHES",
            author: "Jacob Below",
            posString: "Denville",
            pos: { lat: 40.8923, lng: -74.4777 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "fVqW9nDfdto",
            shorts: false
        },
        {
            id: "206",
            title: "SUPPORT",
            author: "Conform Cox",
            posString: "Oss",
            pos: { lat: 51.7643, lng: 5.5185 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "9wOeCFl9GKc",
            shorts: false
        },
        {
            id: "207",
            title: "OLIVE TREE",
            author: "Silvana Roth",
            posString: "Edinburgh",
            pos: { lat: 55.9533, lng: -3.1884 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "etL-EGWS0Es",
            shorts: false
        },
        {
            id: "208",
            title: "YOUR FLAG WILL FLY FOREVER",
            author: "Sharon Vreeburg",
            posString: "Rotterdam",
            pos: { lat: 51.9225, lng: 4.4792 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "bvu2pqYMKUk",
            shorts: false
        },
        {
            id: "209",
            title: "YOUR FLAG WILL FLY FOREVER",
            author: "Sharon Vreeburg",
            posString: "Barcelona",
            pos: { lat: 41.3851, lng: 2.17342 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "bvu2pqYMKUk",
            shorts: false
        },
        {
            id: "210",
            title: "RESILIENCE",
            author: "Hiba Jad",
            posString: "Jeddah",
            pos: { lat: 21.4858, lng: 39.1925 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "YhOmgHqA3vc",
            shorts: false
        },
        {
            id: "211",
            title: "LOVE AND PEACE TO GAZA",
            author: "DARIA Yurishcheva",
            posString: "Marseille",
            pos: { lat: 43.2965, lng: 5.3698 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "sGJvkPIUJiE",
            shorts: false
        },
        {
            id: "212",
            title: "THE TRIED TO BURY US",
            author: "Isa Fraga",
            posString: "Washington DC",
            pos: { lat: 38.8951, lng: -77.0364 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "fnbIYhW_kCs",
            shorts: false
        },
        {
            id: "213",
            title: "THE LIFE OF A WATERMELON",
            author: "Eliane Gordeeff",
            posString: "Almada",
            pos: { lat: 38.6803, lng: -9.1583 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "454lXy1tMLE",
            shorts: false
        },
        {
            id: "214",
            title: "STAY STRONG PALESTINA",
            author: "Sara Moreno, Nicol Cárdenas, Alisson Bayona, Diego Forero, Carla Bareño, Mallivi Melo",
            posString: "Bogotá",
            pos: { lat: 4.711, lng: -74.07211 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "Jt6k0SO28do",
            shorts: false
        },
        {
            id: "215",
            title: "DEFIANCE AGAINST THE WEAPONS",
            author: "Johandry Herrera, Juan Tequia, Mallivi Melo Rey",
            posString: "Bogotá",
            pos: { lat: 4.711, lng: -74.07212 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "C_JYOYrkLT4",
            shorts: false
        },
        {
            id: "216",
            title: "DIGNITY",
            author: "Janet Perlman",
            posString: "Montreal",
            pos: { lat: 45.5019, lng: -73.5674 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "WJVAsY3Cs7Y",
            shorts: false
        },
        {
            id: "217",
            title: "4PAL",
            author: "Jane Cheadle",
            posString: "Brighton",
            pos: { lat: 50.82838, lng: -0.13947 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "n7_4sSf9Kp0",
            shorts: false
        },
        {
            id: "218",
            title: "THE WATERMELON PEACE",
            author: "Daniela González, Carlos Castaño, Luis Castro, Jordy Motavita, Mallivi Melo Rey",
            posString: "Bogotá",
            pos: { lat: 4.711, lng: -74.07213 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "S77tGlBsQcI",
            shorts: false
        },
        {
            id: "219",
            title: "TO GAZA WITH LOVE",
            author: "Cláudio Roberto",
            posString: "Lisbon",
            pos: { lat: 38.7169, lng: -9.13994 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "XmRM5qzY-n4",
            shorts: false
        },
        {
            id: "220",
            title: "WE ARE ALL PALESTINE",
            author: "Manuela Gandra",
            posString: "Lisbon",
            pos: { lat: 38.7169, lng: -9.13992 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "TZTBZvNnov8",
            shorts: false
        },
        {
            id: "221",
            title: "POST-WAR TIREDNESS",
            author: "izza tahir",
            posString: "Nottingham",
            pos: { lat: 52.9548, lng: -1.1581 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "JDCJPX_OAsw",
            shorts: false
        },
        {
            id: "222",
            title: "ÓN ABHAINN GO DTI AN FHARRAIGE",
            author: "Lisa Kearney",
            posString: "Galway",
            pos: { lat: 53.2707, lng: -9.0568 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "a1wykjtuplU",
            shorts: false
        },
        {
            id: "223",
            title: "TO GAZA WITH LOVE",
            author: "Cheryl Blake",
            posString: "Manchester",
            pos: { lat: 53.4808, lng: -2.2427 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "yQB2uq1KFp4",
            shorts: false
        },
        {
            id: "224",
            title: "TO GAZA WITH LOVE",
            author: "Peggy COLLINS",
            posString: "Hamilton",
            pos: { lat: 43.2557, lng: -79.8711 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "LagsZjSZWxk",
            shorts: false
        },
        {
            id: "225",
            title: "TO GAZA",
            author: "Seeti Collective",
            posString: "Delhi",
            pos: { lat: 28.6139, lng: 77.20901 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "1648UK7ZeCo",
            shorts: false
        },
        {
            id: "226",
            title: "WE PLANTED THE SAGE",
            author: "Meghana Bisineer",
            posString: "Oakland",
            pos: { lat: 37.8044, lng: -122.2712 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "T4F6-tGFhIM",
            shorts: false
        },
        {
            id: "227",
            title: "A Flower to Give",
            author: "Lotti Last",
            posString: "Amsterdam",
            pos: { lat: 52.37403, lng: 4.88968 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "xCo2J5vbMG4",
            shorts: false
        },
        {
            id: "228",
            title: "American Sign Language I Love You",
            author: "Jane Flint",
            posString: "Junction City",
            pos: { lat: 44.2193, lng: -123.2049 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "Khx_5RhC_bM",
            shorts: false
        },
        {
            id: "229",
            title: "A Love Letter to Gaza",
            author: "Bridgette Garber",
            posString: "Glen Allen",
            pos: { lat: 37.665, lng: -77.5064 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "hiAd39b4EMY",
            shorts: false
        },
        {
            id: "230",
            title: "Faqqua Iris: National Flower of Palestine",
            author: "Katie Forrester",
            posString: "London",
            pos: { lat: 51.5074, lng: -0.12788 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "6Fqh5NJBtZY",
            shorts: false
        },
        {
            id: "231",
            title: "HANDALA'S WISH",
            author: "Hae-Joon Lee",
            posString: "Los Angeles",
            pos: { lat: 34.05223, lng: -118.2437 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "Eaq4wt7YFD4",
            shorts: false
        },
        {
            id: "232",
            title: "THE FLOWER OF RESISTANCE",
            author: "KATELYNN Duarte",
            posString: "Long Island",
            pos: { lat: 40.7891, lng: -73.135 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "Zrv0Bm4SFns",
            shorts: false
        },
        {
            id: "233",
            title: "LISTEN",
            author: "Erica Moriconi",
            posString: "Ghent",
            pos: { lat: 51.0543, lng: 3.7174 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "9QYFV3R2o10",
            shorts: false
        },
        {
            id: "234",
            title: "FREE",
            author: "Lillian Chan",
            posString: "Toronto",
            pos: { lat: 43.6511, lng: -79.3840 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "UwjKq5vNAWQ",
            shorts: false
        },
        {
            id: "235",
            title: "WHERE THEY BELONG",
            author: "Penny Woolcock",
            posString: "Hackney",
            pos: { lat: 51.545, lng: -0.0552 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "1imiIepfpuk",
            shorts: false
        },
        {
            id: "236",
            title: "SEEDS AND FOOD FOR PEACE",
            author: "Flavia Mertehikian",
            posString: "Pinamar",
            pos: { lat: -37.1085, lng: -56.8612 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "a6yQO97phBw",
            shorts: false
        },
        {
            id: "237",
            title: "ENSEMBLE",
            author: "Faysal Boukari",
            posString: "Paris",
            pos: { lat: 48.8566, lng: 2.3522 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "NjVJaGvEeks",
            shorts: false
        },
        {
            id: "238",
            title: "EYES WIDE SHUT",
            author: "Ana Jacinto Nunes",
            posString: "Lisbon",
            pos: { lat: 38.7169, lng: -9.13991 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "NBHF8Yn2yVE",
            shorts: false
        },
        {
            id: "239",
            title: "SUNBIRDS SWEETS",
            author: "Nick Consedine",
            posString: "Kirkland",
            pos: { lat: 47.6815, lng: -122.2087 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "un2ANMUY1uU",
            shorts: false
        },
        {
            id: "240",
            title: "SEED",
            author: "Sebastien Helias",
            posString: "Urrugne",
            pos: { lat: 43.3631, lng: -1.7017 },
            dateAdded: new Date(2025, 7, 11),
            youtubeId: "8Xz4YAXwtzY",
            shorts: false
        },
    ]
}
