export enum DIMENSIONS {
    LANDSCAPE = 0,
    PORTRAIT,
    SQUARE,
}


export type AnimItem = {
    pos: { lat: number, lng: number }
    posString: string,
    author: string,
    dateAdded: Date,
    youtubeId: string,
    title: string,
    shorts: boolean,
}


export function fetchAnimItems(): AnimItem[] {
    return [
        {
            pos: { lat: 53.1424, lng: -7.6921 },
            posString: "Dublin",
            title: "Light in the Darkness",
            author: "Emlyn Boyle",
            dateAdded: new Date(2025, 6, 13),
            youtubeId: "76mqCOKrpaY",
            shorts: false,
        },
        {
            pos: { lat: 50.8798, lng: 4.7005 },
            posString: "Belguim",
            title: "Bloom",
            author: "Affie De Cooman",
            dateAdded: new Date(2025, 6, 13),
            youtubeId: "7xHW4C9QoRY",
            shorts: false,
        },
        {
            pos: { lat: 37.5079, lng: 15.0830 },
            posString: "Cantina, Italy",
            title: "Give Peace a Chance",
            author: "Donana Napoli",
            youtubeId: "6Pq-oRP-bJs",
            dateAdded: new Date(2025, 6, 13),
            shorts: false,
        },
        {
            pos: { lat: 46.5653, lng: -66.4619 },
            posString: "Canada",
            title: "Surveilance",
            author: "Brandon Hicks",
            dateAdded: new Date(2025, 6, 13),
            youtubeId: "Oe-y2XFiuZI",
            shorts: false,
        },
        {
            pos: { lat: 39.0742, lng: 21.8243 },
            posString: "Greece",
            author: "Konstantinos Kyriakou",
            dateAdded: new Date(2025, 6, 13),
            youtubeId: "PSrN99wuSgU",
            title: "The Sun Thief",
            shorts: false,
        },
        {
            pos: { lat: 29.749907, lng: -95.358421 },
            posString: "Houston, Texas",
            author: "Felipe Sanchez",
            dateAdded: new Date(2025, 6, 13),
            youtubeId: "qMfRjaARVp4",
            title: "KIDS AND ROCKS",
            shorts: false,
        },

        {
            title: "I LOVE WATERMELON",
            author: "Leisl Adams",
            posString: "Ottawa, Canada",
            pos: { lat: 45.42153, lng: -75.69719 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "xZFXwUxzjLA",
            shorts: false,

        },
        {
            title: "WHERE THE OWL APPEARS",
            author: "Shorouk Allam",
            posString: "ASSIUT GOVERNORATE, EGYPT",
            pos: { lat: 26.82055, lng: 30.80250 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "DwDvxZob_Xc",
            shorts: false,
        },
        {
            title: "Existance is Resistance",
            author: "Lluis Fuzzhound",
            posString: "Valencia, Spain",
            pos: { lat: 39.46991, lng: -0.37629 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "6K627N8zx10",
            shorts: false,
        },
        {
            title: "FLOWERS OF MY HEART",
            author: "Adnan Hussain",
            posString: "Los Angeles, US",
            pos: { lat: 34.05223, lng: -118.24368 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "tjiTIeh8WYA",
            shorts: true,
        },
        {
            title: "TO GAZA WITH LOVE",
            author: "Kate Jessop",
            posString: "Brighton, UK",
            pos: { lat: 50.82838, lng: -0.13947 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "yVRvpc7DQNg",
            shorts: false,
        },
        {
            title: "Seeds",
            author: "Vangelis Karadimas",
            posString: "Athens, Greece",
            pos: { lat: 39.0742, lng: 21.8243 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "GXT3BAYbM6E",
            shorts: false,
        },
        {
            pos: { lat: 51.76684, lng: 0.47578 },
            posString: "Essex, UK",
            author: "The Mollusc Dimension",
            dateAdded: new Date(2025, 6, 16),
            shorts: false,
            youtubeId: "d9YzUR9NNmo",
            title: "A TINY MESSAGE OF SOLIDARITY",
        },
        {
            pos: { lat: 19.43260, lng: -99.13320 },
            posString: "Mexico, Mexico City",
            title: "HANDELA BY THE BEACH",
            author: "CUAUHTEMOC PADILLAC",
            youtubeId: "fZVDbCaEcYM",
            shorts: false,
            dateAdded: new Date(2025, 6, 16),
        },
        {
            title: "OLIVES, FLOWERS & SEA",
            author: "Andrés Puig Sandoval",
            posString: "Madrid, Spain",
            pos: { lat: 40.41650, lng: -3.70256 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "NHFyaUmnhGg",
            shorts: false,
        },
        {
            title: "PALESTINE YOU ARE THE HEART OF THE WORLD",
            author: "Ixchel Sierra / Candy C. Rivera",
            posString: "Benito Juárez, Mexico",
            pos: { lat: 19.35000, lng: -99.15000 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "hv4LAzEvSxw",
            shorts: false,
        },
        {
            title: "A SIMPLE TEST",
            author: "Titouan Tillier",
            posString: "Angoulême, France",
            pos: { lat: 45.64842, lng: 0.15519 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "vxsnC6nOJ_M",
            shorts: true,
        },
        {
            pos: { lat: 52.52, lng: 13.4050 },
            title: "Bird",
            author: "Lena Ziyal",
            posString: "Berlin",
            shorts: false,
            youtubeId: "xXLI4QSvOhs",
            dateAdded: new Date(2025, 6, 16),
        },
        {
            title: "REUNITED",
            author: "Dominique Vettom-Morisod",
            posString: "Geneva, Switzerland",
            pos: { lat: 46.20439, lng: 6.14316 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "mWvTUxccDdg",
            shorts: false,
        },
        {
            title: "CHILDREN OF WAR",
            author: "Zina Papadopoulou",
            posString: "Athens, Greece",
            pos: { lat: 39.0742, lng: 21.8243 },
            dateAdded: new Date(2025, 6, 16),
            youtubeId: "mSlATXqkQ9s",
            shorts: false,
        },
        {
            title: "AFTER THE STORM",
            author: "Ben Adam-Harris",
            posString: "Thame, UK",
            pos: { lat: 51.7484, lng: -0.97624 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "hMbeTEY6zV0",
            shorts: false,
        },
        {
            title: "FLOWER CHILD",
            author: "Ed Chee",
            posString: "Vancouver, Canada",
            pos: { lat: 49.2827, lng: -123.1207 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "fmrtvRQ1l_g",
            shorts: false,
        },
        {
            title: "A SMALL WISH",
            author: "Joanne Davis",
            posString: "High Wycombe, UK",
            pos: { lat: 51.6283, lng: -0.7492 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "iGVhI2aYYmc",
            shorts: false,
        },
        {
            title: "HEAVY HEART",
            author: "Stephen Irwin",
            posString: "Wandsworth",
            pos: { lat: 51.4640, lng: -0.1924 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "jIud-8H4fNU",
            shorts: false,
        },
        {
            title: "FROM THE ASHES",
            author: "Jamil Lahham / Dan Franke",
            posString: "Montreal/ Stuttgart",
            pos: { lat: 45.5017, lng: -73.5673 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "7NJ_NL_mHR0",
            shorts: false,
        },
        {
            title: "EXIST TO RESIST",
            author: "Adarsh Madhusudhanan",
            posString: "Kodungallur, India",
            pos: { lat: 10.2222, lng: 76.1992 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "t1fOV5zBIX4",
            shorts: false,
        },
        {
            title: "GAZA SEEDS",
            author: "ELISA MARTINEZ",
            posString: "Alicante, Spain",
            pos: { lat: 38.3452, lng: -0.4815 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "SQG1FtBQiv8",
            shorts: false,
        },
        {
            title: "JUST EATING",
            author: "Mohamed Naser",
            posString: "CAIRO, Egypt",
            pos: { lat: 30.0444, lng: 31.2357 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "rmzqNAIKKrY",
            shorts: true,
        },
        {
            title: "TO GAZA WITH LOVE",
            author: "Saho Saito",
            posString: "Tokyo, Japan",
            pos: { lat: 35.6895, lng: 139.6917 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "FowPfMj9WYc",
            shorts: false,
        },
        {
            title: "HEARTS 4 GAZA",
            author: "Bella Woodfield",
            posString: "Cardiff, UK",
            pos: { lat: 51.4816, lng: -3.1791 },
            dateAdded: new Date(2025, 6, 22),
            youtubeId: "7iTly7Dlwgo",
            shorts: false,
        },
    ]
}
